name: Github Action Example
on:
  pull_request:
  push:
     branches:
       - master
       - develop
    
jobs:
  test:
     name: Running Units Tests
     nuns-on: unbuntu-latest
     
    deploy:
        runs-on: self-hosted
    
    strategy: 
        matrix:
            node-version: [12.x]
            
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
